version: '3'

services:
  # Servicio principal de Rails (servidor web)
  rails:
    # IMAGEN CON TU USUARIO
    image: electroneo/chatwoot-ee-patch:latest
    restart: always
    environment:
      - RAILS_ENV=production
      - NODE_ENV=production
      - INSTALLATION_ENV=docker
      # Estas variables serán inyectadas en Railway
      - FRONTEND_URL=${FRONTEND_URL}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - PORT=3000
    ports:
      - "3000"

  # Servicio de Sidekiq (trabajos asíncronos)
  sidekiq:
    # MISMA IMAGEN
    image: electroneo/chatwoot-ee-patch:latest
    restart: always
    environment:
      - RAILS_ENV=production
      - NODE_ENV=production
      - FRONTEND_URL=${FRONTEND_URL}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']

volumes:
  storage_data:
